version: '3'

networks:
  external:
  internal:

volumes:
  db:
  bundled:

services:
  ##
  # Basic Rails application build image
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/data # mount current directory into the image
      - bundled:/usr/local/bundle
    networks:
      external:
      internal:
    # use tmpfs for tmp and log for performance and to allow
    # multiple builds in parallel. Both directories are mounted
    # into the image AFTER the working directory is mounted.
    tmpfs:
      - /data/log

  ##
  # Development environment for application
  dev: &dev
    <<: *app
    environment:
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
    expose:
      - 3000
    ports:
      - 3000:3000
    command: >
      bash -c "./build/entrypoint.sh &&
      bundle exec puma -C config/puma/development.rb --dir /data --pidfile /data/tmp/pids/puma.pid -b tcp://0.0.0.0:3000 &&
      tail -f log/development.log"
    volumes:
      - .:/data # mount current directory into the image
      - db:/data/db
      - bundled:/usr/local/bundle
